In [ ]:
#Create numpy array and print it
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [1]:
import numpy as np

def temperature_analysis(temperatures):

    average = np.mean(temperatures)

    maximum = np.max(temperatures)

    minimum = np.min(temperatures)

    highest_day = np.argmax(temperatures) + 1

    above_average = temperatures[temperatures > average]

    return average, maximum, minimum, highest_day, above_average


temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

result = temperature_analysis(temperatures)

print("Average temperature:", result[0])
print("Maximum temperature:", result[1])
print("Minimum temperature:", result[2])
print("Day with highest temperature: Day", result[3])
print("Temperatures above average:", result[4])

Average temperature: 31.842857142857145
Maximum temperature: 34.5
Minimum temperature: 29.8
Day with highest temperature: Day 5
Temperatures above average: [32.5 33.1 34.5]


In [2]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

first_row = arr[0, :]

last_row = arr[-1, :]

first_column = arr[:, 0]

last_column = arr[:, -1]

middle = arr[0:2, 1:3]

alternate = arr.flatten()[::2]

shape = arr.shape

dimensions = arr.ndim

total_elements = arr.size


print("Array:")
print(arr)

print("First row:", first_row)
print("Last row:", last_row)
print("First column:", first_column)
print("Last column:", last_column)
print("Middle 2x2 section:")
print(middle)
print("Every alternate element:", alternate)

print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Total elements:", total_elements)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
First column: [1 5 9]
Last column: [ 4  8 12]
Middle 2x2 section:
[[2 3]
 [6 7]]
Every alternate element: [ 1  3  5  7  9 11]
Shape: (3, 4)
Number of dimensions: 2
Total elements: 12


In [3]:
import numpy as np

arr = np.arange(1, 51)

even = arr[arr % 2 == 0]

odd = arr[arr % 2 != 0]

print("Original array:", arr)
print("Even numbers:", even)
print("Odd numbers:", odd)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Odd numbers: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
import numpy as np

arr = np.random.randint(1, 101, 30)

print("Generated array:")
print(arr)

# Values greater than 50
greater_50 = arr[arr > 50]

# Values between 25 and 75
between_25_75 = arr[(arr >= 25) & (arr <= 75)]

# Count values greater than 50
count = np.sum(arr > 50)

# Average of values greater than 50
average = np.mean(greater_50)

print("Values greater than 50:", greater_50)
print("Values between 25 and 75:", between_25_75)
print("Count greater than 50:", count)
print("Average of values greater than 50:", average)

Generated array:
[ 9  3 89 42 87 96  8 53  8  8 23 17 51 97 92 67 48 20 34 36 50 58 87 66
 74 68  8 19 96 61]
Values greater than 50: [89 87 96 53 51 97 92 67 58 87 66 74 68 96 61]
Values between 25 and 75: [42 53 51 67 48 34 36 50 58 66 74 68 61]
Count greater than 50: 15
Average of values greater than 50: 76.13333333333334
