In [ ]:
#Create numpy array and print it
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

In [ ]:
import numpy as np

def temperature_analysis(temperatures):

    average = np.mean(temperatures)

    maximum = np.max(temperatures)

    minimum = np.min(temperatures)

    highest_day = np.argmax(temperatures) + 1

    above_average = temperatures[temperatures > average]

    return average, maximum, minimum, highest_day, above_average


temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

result = temperature_analysis(temperatures)

print("Average temperature:", result[0])
print("Maximum temperature:", result[1])
print("Minimum temperature:", result[2])
print("Day with highest temperature: Day", result[3])
print("Temperatures above average:", result[4])

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

first_row = arr[0, :]

last_row = arr[-1, :]

first_column = arr[:, 0]

last_column = arr[:, -1]

middle = arr[0:2, 1:3]

alternate = arr.flatten()[::2]

shape = arr.shape

dimensions = arr.ndim

total_elements = arr.size


print("Array:")
print(arr)

print("First row:", first_row)
print("Last row:", last_row)
print("First column:", first_column)
print("Last column:", last_column)
print("Middle 2x2 section:")
print(middle)
print("Every alternate element:", alternate)

print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Total elements:", total_elements)

In [ ]:
import numpy as np

arr = np.arange(1, 51)

even = arr[arr % 2 == 0]

odd = arr[arr % 2 != 0]

print("Original array:", arr)
print("Even numbers:", even)
print("Odd numbers:", odd)

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, 30)

print("Generated array:")
print(arr)

# Values greater than 50
greater_50 = arr[arr > 50]

# Values between 25 and 75
between_25_75 = arr[(arr >= 25) & (arr <= 75)]

# Count values greater than 50
count = np.sum(arr > 50)

# Average of values greater than 50
average = np.mean(greater_50)

print("Values greater than 50:", greater_50)
print("Values between 25 and 75:", between_25_75)
print("Count greater than 50:", count)
print("Average of values greater than 50:", average)

In [ ]:
import numpy as np

marks = np.array([
    [78, 82, 91],  
    [65, 74, 80],  
    [92, 88, 95],  
    [56, 69, 72],  
    [84, 90, 87]   
])

student_avg = np.mean(marks, axis=1)

subject_avg = np.mean(marks, axis=0)

highest = np.max(marks)

lowest = np.min(marks)

highest_student = np.argmax(student_avg) + 1

subjects = ["Mathematics", "Physics", "Programming"]
highest_subject = subjects[np.argmax(subject_avg)]

print("Marks Matrix:")
print(marks)

print("\nAverage marks of each student:")
for i, avg in enumerate(student_avg):
    print(f"Student {i+1}: {avg:.2f}")

print("\nAverage marks in each subject:")
for subject, avg in zip(subjects, subject_avg):
    print(f"{subject}: {avg:.2f}")

print("\nHighest mark:", highest)
print("Lowest mark:", lowest)
print("Student with highest average: Student", highest_student)
print("Subject with highest average:", highest_subject)

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# 1. Addition
addition = A + B

# 2. Subtraction
subtraction = A - B

# 3. Element-wise multiplication
element_multiplication = A * B

# 4. Matrix multiplication
matrix_multiplication = A @ B

# Display results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(element_multiplication)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

In [ ]:
import numpy as np

def transform_data(data):
    data = np.array(data)

    square = data ** 2
    square_root = np.sqrt(data)
    exponential = np.exp(data)

    mean_square = np.mean(square)
    mean_square_root = np.mean(square_root)
    mean_exponential = np.mean(exponential)

    print("Original Data:", data)
    print("Square:", square)
    print("Square Root:", square_root)
    print("Exponential:", exponential)

    print("Mean of Square:", mean_square)
    print("Mean of Square Root:", mean_square_root)
    print("Mean of Exponential:", mean_exponential)


measurements = [2, 4, 6, 8, 10, 12]

transform_data(measurements)

In [ ]:
import numpy as np

data = np.arange(1, 25)

print("Original Array is :")
print(data)

array_4x6 = data.reshape(4, 6)
print("\n4 x 6 Array:")
print(array_4x6)
print("Shape:", array_4x6.shape)

array_6x4 = data.reshape(6, 4)
print("\n6 x 4 Array:")
print(array_6x4)
print("Shape:", array_6x4.shape)

array_2x3x4 = data.reshape(2, 3, 4)
print("\n2 x 3 x 4 Array:")
print(array_2x3x4)
print("Shape:", array_2x3x4.shape)

one_dimensional = array_4x6.reshape(-1)

print("\nBack to 1D Array:")
print(one_dimensional)
print("Shape:", one_dimensional.shape)

In [ ]:
import numpy as np

experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

one_dimensional = np.concatenate((experiment_1, experiment_2))

print("One-Dimensional Array:")
print(one_dimensional)
print("Shape:", one_dimensional.shape)


rows = np.vstack((experiment_1, experiment_2))

print("\nMatrix with Experiments as Rows:")
print(rows)
print("Shape:", rows.shape)


columns = np.column_stack((experiment_1, experiment_2))

print("\nMatrix with Experiments as Columns:")
print(columns)
print("Shape:", columns.shape)

One-Dimensional Array:
[10 20 30 40 50 15 25 35 45 55]
Shape: (10,)

Matrix with Experiments as Rows:
[[10 20 30 40 50]
 [15 25 35 45 55]]
Shape: (2, 5)

Matrix with Experiments as Columns:
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
Shape: (5, 2)
