In [1]:
#creating numpy array

import numpy as np

num=np.array([2,3,4,5,6,7,8,9])
print(num)

[2 3 4 5 6 7 8 9]


In [ ]:
#Dimension of Numpy Array

a=np.array([1,2,3,4,5]) #one dimension

print(a)

b=np.array([
    [1,2,3,], #Two dimension
    [5,6,7]

])
print(b)



c = np.array([
    [
        [1, 2],  #3 dimesion
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(c)

[1 2 3 4 5]
[[1 2 3]
 [5 6 7]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#Check how many dimension are present in array used 
#nidm

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [9]:
#Check shape of array along each dimensions
#used shape

print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [ ]:
#Check size of give array how many num are present in array
#used size

print(a.size)
print(b.size)
print(c.size)

#check which data type of array
print(a.dtype)



5
6
8
int64


In [13]:
#Indexing the array 
#indexing means accing a particular array element

d=np.array([1,2,3,4,5,6,7])
print(d[4])

5


In [14]:
#Slicing 
#slicing means taking a portion of an array

print(d[1:4])

[2 3 4]


In [15]:
#Mathematical operators
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [17]:
#Important Numpy functions

#np.zeros()
#Creates an array filled with zeros.
a = np.zeros(5)
print(a)

#np.ones
a = np.ones(5)
print(a)

#np.arange
#creates values within range
a = np.arange(1, 10)
print(a)


#np.linspace()
#Creates evenly spaced numbers.
a = np.linspace(0, 10, 5)
print(a)


#reshape
#reshape() changes the structure/shape of an array without changing its data.
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)



#Aggregation functions

a = np.array([10, 20, 30, 40])
print(np.sum(a)) #Calculate sum of array

print(np.mean(a))#Calculate mean

print(np.max(a))#calculate maximum in array

print(np.min(a))


print(np.std(a))#calculate standard deviation in array




[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]
[[1 2 3]
 [4 5 6]]
100
25.0
40
10
11.180339887498949
