In [2]:
#arithmatic operations

a=10
b=23

print("Addition of a and b is:",a+b)
print("Subtraction of a and b is:",a-b)
print("Multiplication of a and b is:",a*b)
print("Division of a and b is:",a/b)
print("Modulus of a and b is:",a%b)
print("Square of a and b is:",a**b)





Addition of a and b is: 33
Subtraction of a and b is: -13
Multiplication of a and b is: 230
Division of a and b is: 0.43478260869565216
Modulus of a and b is: 10
Square of a and b is: 100000000000000000000000


In [3]:
#Assignment operators

num=10
num=num+5
print("Value of num after addition is:",num)

num=10
num+=5
print("Value of num after addition is:",num)

num=10
num-=5
print("Value of num after subtraction is:",num)

num=10
num*=5
print("Value of num after multiplication is:",num)


num=10
num/=5
print("Value of num after division is:",num)

Value of num after addition is: 15
Value of num after addition is: 15
Value of num after subtraction is: 5
Value of num after multiplication is: 50
Value of num after division is: 2.0


In [4]:
#Logical operators

print("not False is:",not False)
print("True and False is:",True and False)

not False is: True
True and False is: False


In [5]:
name = input("Enter your name:")
print("hello",name)

hello Abhijeet


In [6]:
#Relational operations
a=10
b=23
print("a is equal to b:",a==b)
print("a is not equal to b:",a!=b)
print("a is greater than b:",a>b)
print("a is less than b:",a<b)
print("a is greater than or equal to b:",a>=b)
print("a is less than or equal to b:",a<=b)

a is equal to b: False
a is not equal to b: True
a is greater than b: False
a is less than b: True
a is greater than or equal to b: False
a is less than or equal to b: True


In [4]:
#Python Data Structures Operations

#List Operations

list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print("List1 is:",list1)
print("List2 is:",list2)

print("Concatenation of list1 and list2 is:",list1+list2)

list1.append(11)
print("List1 after appending 11 is:",list1)

list1.insert(0,11)
print("List1 after inserting 11 at index 0 is:",list1)
list1.remove(3)
print("List1 after removing 3 is:",list1)
list1.pop(4)
print("List1 after popping element at index 4 is:",list1)

list2.sort()
print("List2 after sorting is:",list2)
list2.reverse()
print("List2 after reversing is:",list2)




List1 is: [1, 2, 3, 4, 5]
List2 is: [6, 7, 8, 9, 10]
Concatenation of list1 and list2 is: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List1 after appending 11 is: [1, 2, 3, 4, 5, 11]
List1 after inserting 11 at index 0 is: [11, 1, 2, 3, 4, 5, 11]
List1 after removing 3 is: [11, 1, 2, 4, 5, 11]
List1 after popping element at index 4 is: [11, 1, 2, 4, 11]
List2 after sorting is: [6, 7, 8, 9, 10]
List2 after reversing is: [10, 9, 8, 7, 6]


In [ ]:
#Tuple Operations

tuple=(2,3,4,5,6,7,8,9,10)
print("Tuple is:",tuple)
print("Element at index 2 is:",tuple[2])
print("Slice of tuple from index 0 to 5 is:",tuple[0:5])




Tuple is: (2, 3, 4, 5, 6, 7, 8, 9, 10)
Element at index 2 is: 4
Slice of tuple from index 0 to 5 is: (2, 3, 4, 5, 6)


In [9]:
l1={1,2,3,4,5,6}
l2={7,8,9,10,11}
prod=[]
for i in range(len(l1)):
    print(l1[i]*l2[i])
    prod.append(l1[i]*l2[i])

    print("Product of l1 and l2 is:",prod)
    



TypeError: 'set' object is not subscriptable

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])

print("array",a)
print("Type",type(a))
print("Shape of array is:",a.shape)
print("Data type",a.dtype)
print("Dimension of array is:",a.ndim)
print("Size",a.size )


array [1 2 3 4 5]
Type <class 'numpy.ndarray'>
Shape of array is: (5,)
Data type int64
Dimension of array is: 1
Size 5


In [ ]:
arr1=np.array([1,2,3,4,5,6,7])

print("Array 1:", arr1)
arr2=np.arange(1,6)
print("Array 2:", arr2)
arr3=np.zeros(5)
print("Array 3:", arr3) 
arr4=np.ones(5)
arr5=np.linspace(1,10,5)
arr6=np.empty(5)

Array 1: [1 2 3 4 5 6 7]
Array 2: [1 2 3 4 5]
Array 3: [0. 0. 0. 0. 0.]


In [21]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Array 1:", arr1)


arr1=arr1.reshape(3,3)
print(arr1)


Array 1: [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Flatten: returns a copy
flattened_array = arr.flatten()
print("Flattened array:", flattened_array)

# Ravel: returns a flattened view when possible
raveled_array = arr.ravel()
print("Raveled array:", raveled_array)

Flattened array: [1 2 3 4 5 6 7 8 9]
Raveled array: [1 2 3 4 5 6 7 8 9]
