In [5]:
#print first and last element of the array
import numpy as np

a=np.array([10,20,30,40,50,60,70,80,90,100])

print(a)

print("First element:", a[0])
print("Last element:", a[-1])

[ 10  20  30  40  50  60  70  80  90 100]
First element: 10
Last element: 100


In [7]:
#Print 20 30 and 40 from the array

print("Original array:", a)
print("Elements 20, 30, and 40:", a[1:4])  #used slicing here

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Elements 20, 30, and 40: [20 30 40]


In [12]:
#create array of 20 zeros

a=np.zeros(20)

print("array of 20 zeros:", a)


array of 20 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#create array 1 to 20 using arange
import numpy as np

a=np.arange(0,21)

print("array from 1 to 20:", a)

even_number = a[a%2==0]

print("Even numbers from 1 to 20:", even_number)    

array from 1 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers from 1 to 20: [ 0  2  4  6  8 10 12 14 16 18 20]


In [1]:
#create array 1 to 12 and reshape it into 3*4
import numpy as np   
a=np.arange(1,13)   

a=a.reshape(3,4)   

print("Array from 1 to 12 reshaped into 3x4:\n", a)


Array from 1 to 12 reshaped into 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np

a=np.array([
    [1,2,3],
     [4,5,6],
    [7,8,9],
    [10,11,12]
])
print("Original array:\n", a)

row_mean=np.mean(a, axis=1)  # Calculate mean along rows
col_mean=np.mean(a, axis=0)  # Calculate mean along columns 

print("Mean of each row:", row_mean)



Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Mean of each row: [ 2.  5.  8. 11.]
